services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: kostify
      POSTGRES_PASSWORD: kostify
      POSTGRES_DB: kostify
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kostify -d kostify"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  minio:
    image: minio/minio:latest
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: kostify
      MINIO_ROOT_PASSWORD: kostify123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  api:
    build: ./backend
    environment:
      APP_ENV: production
      APP_PORT: "8080"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: kostify
      DB_PASSWORD: kostify
      DB_NAME: kostify
      REDIS_ADDR: redis:6379
      JWT_SECRET: dev-secret-ganti-di-produksi-jangan-pakai-ini
      ACCESS_TOKEN_TTL: 15m
      REFRESH_TOKEN_TTL: 168h
      COOKIE_SECURE: "false"
      COOKIE_DOMAIN: ""
      FRONTEND_ORIGIN: http://localhost:5173
      AUTO_MIGRATE: "true"
      MIGRATIONS_DIR: /app/migrations
      BCRYPT_COST: "12"
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: kostify
      MINIO_SECRET_KEY: kostify123
      MINIO_BUCKET: kostify
      MINIO_SECURE: "false"
      MINIO_PUBLIC_URL: http://localhost:9000
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

volumes:
  pgdata:
  redisdata:
  miniodata:
